pkg/apis/scoby.triggermesh.io/common/status.go
pkg/apis/scoby.triggermesh.io/common/status_test.go

Status initialization had some issues when the status was previously set with non default values.
Fixing them.

Fix status initialization

---

config/scoby.triggermesh.io_crdregistrations.yaml
docs/samples/01.kuard/01.generic-registration.yaml
docs/samples/01.kuard/02.kuard-crd.yaml
docs/samples/01.kuard/03.kuard-instance.yaml
pkg/apis/scoby.triggermesh.io/common/formfactor_types.go
pkg/reconciler/component/reconciler/deployment/reconciler.go
pkg/reconciler/component/reconciler/knservice/reconciler.go
pkg/reconciler/component/reconciler/render/podspec.go
pkg/reconciler/component/registry/registry.go
pkg/reconciler/registration/crd/reconcile.go

Add service to deployments

---

pkg/reconciler/component/reconciler/builder.go
pkg/reconciler/component/reconciler/deployment/reconciler.go
pkg/reconciler/component/reconciler/knservice/reconciler.go
pkg/reconciler/component/reconciler/render/crd.go
pkg/reconciler/component/registry/registry.go
pkg/reconciler/semantic/semantic.go

- Fix semantic comparison for service
- Prepare status work by passing CRD to component reconciler

Fix semantic comparison for service

---

docs/samples/01.kuard/02.kuard-crd.yaml
pkg/reconciler/component/reconciler/knservice/reconciler.go
pkg/reconciler/component/reconciler/render/crd _test.go
pkg/reconciler/component/reconciler/render/crd.go

Related to https://github.com/triggermesh/scoby/issues/29

CRD status analisys

---

pkg/reconciler/component/reconciler/base/object/rendered.go
pkg/reconciler/component/reconciler/base/object/rendered_test.go

Fix and write test for deep nesting rendering.
While preparing tests for rendering ConfigMaps and Secrets an issue was found where a 3 level nesting rendering would not work as expected.
Also replacing rendering with static values is fixed/tested.

Tests: fix deeply nested rendering issue

---

pkg/reconciler/component/reconciler/base/object/rendered.go
pkg/reconciler/component/reconciler/base/object/rendered_test.go
pkg/reconciler/resources/container.go
pkg/reconciler/resources/container_test.go

Add fixes and tests for rendering parameters as secrets and configmaps.

Test: add more rendering tests

---

docs/samples/01.kuard/08.param.add.metadata/01.kuard-registration.yaml
docs/samples/01.kuard/08.param.add.metadata/02.kuard-instance.yaml
pkg/reconciler/component/reconciler/base/object/rendered.go

Closes https://github.com/triggermesh/scoby/issues/46

Render: add envvars from scratch

---

docs/registration.md
docs/samples/01.kuard/01.kuard-crd.yaml
docs/status.md
pkg/apis/scoby.triggermesh.io/v1alpha1/crdregistration_lifecycle.go
pkg/reconciler/component/reconciler/base/crd/crd _test.go
pkg/reconciler/component/reconciler/base/crd/crd.go
pkg/reconciler/component/reconciler/base/object/reconciling.go
pkg/reconciler/component/reconciler/base/object/rendered.go
pkg/reconciler/component/reconciler/base/object/rendered_test.go
pkg/reconciler/component/reconciler/base/resolver/resolver.go
pkg/reconciler/component/reconciler/base/resolver/resolver_test.go
pkg/reconciler/component/reconciler/base/status/status.go
pkg/reconciler/component/reconciler/builder.go
pkg/reconciler/component/reconciler/deployment/reconciler.go
pkg/reconciler/component/reconciler/knservice/reconciler.go

Closes https://github.com/triggermesh/scoby/issues/66

Status: support addressables

---

README.md
docs/getting-started/README.md
docs/samples/01.kuard/03.param.skip/01.kuard-registration.yaml
docs/samples/01.kuard/04.param.rename/01.kuard-registration.yaml

Add getting started: rename param example

Docs: rename param example

---

docs/getting-started/README.md
docs/samples/01.kuard/07.param.configmap/01.kuard-registration.yaml
docs/samples/01.kuard/08.param.addressable/02.kuard-instance.yaml
docs/samples/01.kuard/08.param.addressable/03.memory-broker.yaml
docs/samples/01.kuard/08.param.addressable/03.service.yaml
docs/samples/01.kuard/09.param.add.metadata/01.kuard-registration.yaml

Add getting started cases for addressabel and addEnvVar

Docs: add getting started cases for addressable and addEnvVar

---

cmd/scoby-controller/main.go
pkg/apis/scoby/v1alpha1/crdregistration_lifecycle.go
pkg/reconciler/component/reconciler/base/renderer/renderer.go
pkg/reconciler/component/reconciler/builder/builder.go
pkg/reconciler/component/reconciler/deployment/reconciler.go
pkg/reconciler/component/reconciler/interfaces.go
pkg/reconciler/component/registry/registry.go
pkg/reconciler/registration/crd/reconcile.go
pkg/reconciler/registration/crd/suite_test.go
pkg/reconciler/resolver/resolver.go
pkg/reconciler/resolver/resolver_test.go

URL parsing, adding the resolved address as annotation.
Related to #50 and #49

Hook: url parsing

---

docs/hooks.md
pkg/apis/common/v1alpha1/hook.go
pkg/apis/common/v1alpha1/interface.go
pkg/apis/common/v1alpha1/status.go
pkg/apis/scoby/v1alpha1/crdregistration_lifecycle.go
pkg/reconciler/component/reconciler/base/reconciler.go
pkg/reconciler/component/reconciler/builder/builder.go
pkg/reconciler/component/reconciler/hook/reconciler.go
pkg/reconciler/component/reconciler/interfaces.go
pkg/reconciler/registration/crd/reconcile.go

Call hook on reconcile.
Still the hook reconciler does not inspect the response.

Hooks: call hook on reconcile

---

config/200-clusterrole-addressable-resolvers-kn.yaml
config/200-clusterroles.yaml
config/500-scoby-controller.yaml

Replace copy paste data with Scoby specifics.

Update clusterroles labels

---

pkg/reconciler/component/reconciler/base/reconciler.go
pkg/reconciler/component/reconciler/base/status/status.go
pkg/reconciler/component/reconciler/builder/builder.go
pkg/reconciler/component/reconciler/deployment/reconciler.go
pkg/reconciler/component/reconciler/hook/reconciler.go
pkg/reconciler/component/reconciler/interfaces.go
pkg/reconciler/component/reconciler/knservice/reconciler.go

Closes https://github.com/triggermesh/scoby/issues/104

Improve status from hook

---

docs/getting-started/README.md
docs/registration.md
pkg/component/reconciler/formfactor/deployment/reconciler.go
pkg/component/reconciler/formfactor/knservice/reconciler.go

Generated resources will include the registration type as a prefix.

Add reg type to generated resources

---

pkg/component/reconciler/base/renderer/renderer.go
pkg/component/reconciler/base/renderer/renderer_test.go

fixes https://github.com/triggermesh/scoby/issues/132

Render: fix addenv render loop ref

---

docs/samples/02.webhooksource/02.webhooksource-registration.yaml
docs/samples/03.kafkasource/02.kafkasource-registration.yaml
docs/triggermesh/README.md

- Restructure TriggerMesh migration to avoid repeated content.
- Add `kafkasource` section

Docs: add kafkasource migration docs

---

docs/samples/03.kafkasource/02.kafkasource-registration.yaml
docs/samples/04.httppollersource/02.httppollersource-registration.yaml
docs/samples/05.httptarget/02.httptarget-registration.yaml
docs/samples/06.kafkatarget/02.kafkatarget-registration.yaml
docs/triggermesh/README.md

Add TriggerMesh target samples.
Improve secret registration.

Docs: add triggermesh target samples

---

docs/triggermesh/README.md

TriggerMesh CRDs location fix.

Fix: URL for CRDs

---

config/300-crdregistration.yaml
docs/samples/01.kuard/02.kuard-clusterrole.yaml
pkg/apis/common/v1alpha1/hook.go
pkg/apis/hook/v1/types.go
pkg/component/builder/builder.go
pkg/component/reconciler/base/reconciler.go
pkg/component/reconciler/base/status/status.go
pkg/component/reconciler/formfactor/deployment/reconciler.go
pkg/component/reconciler/formfactor/knservice/reconciler.go
pkg/component/reconciler/hook/reconciler.go
pkg/component/reconciler/interfaces.go

Hooks will now be able to modify all pre-rendered children of an object.

Hooks: introduce new prerender api for hooks

---

docs/hooks-tutorial.md
docs/install.md

Fixing some docs typos on tutorial.

Hooks: fix doc typos
